name: CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest  # Since your code specifically requires Windows

    steps:
      - uses: actions/checkout@v4

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgGitCommitId: master

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # Add this step if you have tests
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

      - name: Static Analysis (cppcheck)
        run: |
          cmake --build ${{github.workspace}}/build --target cppcheck

      # Optional: Package the application
      - name: Package
        run: |
          cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/install

      # Optional: Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CountVonCount-Windows
          path: ${{github.workspace}}/install/